default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: 3306
  encoding: utf8mb4
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Mars_development

test:
  <<: *default
  database: Mars_test

production:
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] || 'mars' %>
  password: <%= ENV['DB_PASSWORD'] || 'mars_mysql' %>
  host: localhost
  port: 3306
  encoding: utf8mb4
  database: mars
